name: project-3
channels:
  - defaults

dependencies:
  - python=3.6.8
  - matplotlib=3.1.3
  - numpy==1.18.1
  - pillow==7.0.0
  - pip=19.0.3
  - pandas=1.0.1
  - scikit-learn=0.21.3
  - seaborn=0.9.0
  - statsmodels=0.10.1
  - pip:
    - pytest==4.6.3
    - sqlalchemy==1.3.8
